from __future__ import annotations

from collections.abc import Mapping
from contextlib import closing
from dataclasses import dataclass
from pathlib import Path

from .db_runtime import (
    backend_name_for_connection,
    connect_database,
    database_exists,
    resolve_database_runtime,
    table_columns_from_connection,
    table_names_from_connection,
)
from .jobs.identity import (
    build_job_identity,
    normalize_optional_metadata,
)

REQUIRED_TABLES = (
    "jobs",
    "applications",
    "application_tracking",
    "session_history",
    "source_registry",
)

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS source_registry (
    id INTEGER PRIMARY KEY,
    source_url TEXT NOT NULL,
    normalized_url TEXT NOT NULL,
    portal_type TEXT,
    company TEXT,
    label TEXT,
    status TEXT NOT NULL DEFAULT 'manual_review',
    first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_verified_at TEXT,
    notes TEXT,
    provenance TEXT,
    verification_reason_code TEXT,
    verification_reason TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
    id INTEGER PRIMARY KEY,
    source TEXT NOT NULL,
    source_job_id TEXT,
    company TEXT NOT NULL,
    title TEXT NOT NULL,
    location TEXT,
    apply_url TEXT,
    portal_type TEXT,
    salary_text TEXT,
    posted_at TEXT,
    found_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ingest_batch_id TEXT,
    source_query TEXT,
    import_source TEXT,
    source_registry_id INTEGER,
    canonical_apply_url TEXT,
    identity_key TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    raw_json TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (source_registry_id) REFERENCES source_registry(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS applications (
    id INTEGER PRIMARY KEY,
    job_id INTEGER NOT NULL,
    state TEXT NOT NULL DEFAULT 'draft',
    resume_variant TEXT,
    notes TEXT,
    last_attempted_at TEXT,
    applied_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS application_tracking (
    id INTEGER PRIMARY KEY,
    job_id INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS session_history (
    id INTEGER PRIMARY KEY,
    manifest_path TEXT NOT NULL,
    item_count INTEGER NOT NULL,
    launchable_count INTEGER NOT NULL,
    ingest_batch_id TEXT,
    source_query TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_jobs_apply_url ON jobs(apply_url);
CREATE INDEX IF NOT EXISTS idx_jobs_source_company_title_location
ON jobs(source, company, title, location);
CREATE INDEX IF NOT EXISTS idx_applications_job_id ON applications(job_id);
CREATE INDEX IF NOT EXISTS idx_application_tracking_job_id ON application_tracking(job_id);
CREATE INDEX IF NOT EXISTS idx_session_history_created_at ON session_history(created_at);
CREATE INDEX IF NOT EXISTS idx_session_history_ingest_batch_id ON session_history(ingest_batch_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_source_registry_normalized_url ON source_registry(normalized_url);
CREATE INDEX IF NOT EXISTS idx_source_registry_status ON source_registry(status);
CREATE INDEX IF NOT EXISTS idx_source_registry_last_verified_at ON source_registry(last_verified_at);
"""

POST_SCHEMA_SQL = """
CREATE INDEX IF NOT EXISTS idx_jobs_ingest_batch_id ON jobs(ingest_batch_id);
CREATE INDEX IF NOT EXISTS idx_jobs_canonical_apply_url ON jobs(canonical_apply_url);
CREATE INDEX IF NOT EXISTS idx_jobs_identity_key ON jobs(identity_key);
CREATE INDEX IF NOT EXISTS idx_jobs_source_registry_id ON jobs(source_registry_id);
"""

POSTGRES_BASE_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS source_registry (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_url TEXT NOT NULL,
        normalized_url TEXT NOT NULL,
        portal_type TEXT,
        company TEXT,
        label TEXT,
        status TEXT NOT NULL DEFAULT 'manual_review',
        first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        last_verified_at TEXT,
        notes TEXT,
        provenance TEXT,
        verification_reason_code TEXT,
        verification_reason TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS jobs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source TEXT NOT NULL,
        source_job_id TEXT,
        company TEXT NOT NULL,
        title TEXT NOT NULL,
        location TEXT,
        apply_url TEXT,
        portal_type TEXT,
        salary_text TEXT,
        posted_at TEXT,
        found_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        ingest_batch_id TEXT,
        source_query TEXT,
        import_source TEXT,
        source_registry_id BIGINT,
        canonical_apply_url TEXT,
        identity_key TEXT,
        status TEXT NOT NULL DEFAULT 'new',
        raw_json TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        FOREIGN KEY (source_registry_id) REFERENCES source_registry(id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS applications (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id BIGINT NOT NULL,
        state TEXT NOT NULL DEFAULT 'draft',
        resume_variant TEXT,
        notes TEXT,
        last_attempted_at TEXT,
        applied_at TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS application_tracking (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id BIGINT NOT NULL,
        status TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS session_history (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        manifest_path TEXT NOT NULL,
        item_count INTEGER NOT NULL,
        launchable_count INTEGER NOT NULL,
        ingest_batch_id TEXT,
        source_query TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
    )
    """,
)

POSTGRES_SECONDARY_INDEX_STATEMENTS = (
    """
    CREATE INDEX IF NOT EXISTS idx_jobs_apply_url ON jobs(apply_url)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_jobs_source_company_title_location
    ON jobs(source, company, title, location)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_applications_job_id ON applications(job_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_application_tracking_job_id ON application_tracking(job_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_session_history_created_at ON session_history(created_at)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_session_history_ingest_batch_id ON session_history(ingest_batch_id)
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS idx_source_registry_normalized_url ON source_registry(normalized_url)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_source_registry_status ON source_registry(status)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_source_registry_last_verified_at ON source_registry(last_verified_at)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_jobs_ingest_batch_id ON jobs(ingest_batch_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_jobs_canonical_apply_url ON jobs(canonical_apply_url)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_jobs_identity_key ON jobs(identity_key)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_jobs_source_registry_id ON jobs(source_registry_id)
    """,
)

JOB_INSERT_SQL = """
INSERT INTO jobs (
    source,
    source_job_id,
    company,
    title,
    location,
    apply_url,
    portal_type,
    salary_text,
    posted_at,
    found_at,
    ingest_batch_id,
    source_query,
    import_source,
    source_registry_id,
    canonical_apply_url,
    identity_key,
    raw_json
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    COALESCE(?, CURRENT_TIMESTAMP),
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
"""

EXACT_APPLY_URL_MATCH_SQL = """
SELECT id
FROM jobs
WHERE apply_url = ?
LIMIT 1
"""

CANONICAL_APPLY_URL_MATCH_SQL = """
SELECT id
FROM jobs
WHERE canonical_apply_url = ?
LIMIT 1
"""

IDENTITY_KEY_MATCH_SQL = """
SELECT id
FROM jobs
WHERE identity_key = ?
LIMIT 1
"""

GET_INGEST_BATCH_SUMMARY_SQL = """
SELECT
    ingest_batch_id,
    MIN(source_query) AS source_query,
    MIN(import_source) AS import_source,
    COUNT(*) AS job_count
FROM jobs
WHERE ingest_batch_id = ?
GROUP BY ingest_batch_id
LIMIT 1
"""

SESSION_HISTORY_INSERT_SQL = """
INSERT INTO session_history (
    manifest_path,
    item_count,
    launchable_count,
    ingest_batch_id,
    source_query,
    created_at
) VALUES (?, ?, ?, ?, ?, COALESCE(?, CURRENT_TIMESTAMP))
"""

LIST_RECENT_SESSION_HISTORY_SQL = """
SELECT
    id,
    manifest_path,
    item_count,
    launchable_count,
    ingest_batch_id,
    source_query,
    created_at
FROM session_history
ORDER BY created_at DESC, id DESC
LIMIT ?
"""

GET_SESSION_HISTORY_BY_ID_SQL = """
SELECT
    id,
    manifest_path,
    item_count,
    launchable_count,
    ingest_batch_id,
    source_query,
    created_at
FROM session_history
WHERE id = ?
LIMIT 1
"""


@dataclass(frozen=True, slots=True)
class DuplicateJobMatch:
    job_id: int
    rule: str
    matched_value: str


@dataclass(frozen=True, slots=True)
class IngestBatchSummary:
    batch_id: str
    source_query: str | None
    import_source: str | None
    job_count: int


@dataclass(frozen=True, slots=True)
class SessionHistoryEntry:
    session_id: int
    manifest_path: Path
    item_count: int
    launchable_count: int
    batch_id: str | None
    source_query: str | None
    created_at: str


def initialize_schema(database_path: Path, *, backfill_identity: bool = True) -> None:
    runtime = resolve_database_runtime(database_path)
    if runtime.backend == "sqlite" and not runtime.sqlite_path.exists():
        database_path.parent.mkdir(parents=True, exist_ok=True)
    with closing(connect_database(database_path)) as connection:
        _initialize_schema_connection(
            connection,
            backfill_identity=backfill_identity,
            include_secondary_indexes=True,
        )
        connection.commit()


def existing_tables(database_path: Path) -> set[str]:
    if not database_exists(database_path):
        return set()

    with closing(connect_database(database_path)) as connection:
        return table_names_from_connection(connection)


def missing_required_tables(database_path: Path) -> list[str]:
    return sorted(set(REQUIRED_TABLES) - existing_tables(database_path))


def schema_exists(database_path: Path) -> bool:
    return database_exists(database_path) and not missing_required_tables(database_path)


def insert_job(connection, job_record: Mapping[str, object]) -> int:
    identity = build_job_identity(job_record)
    cursor = connection.execute(
        JOB_INSERT_SQL,
        (
            job_record["source"],
            job_record.get("source_job_id"),
            job_record["company"],
            job_record["title"],
            job_record["location"],
            job_record["apply_url"],
            job_record.get("portal_type"),
            job_record.get("salary_text"),
            job_record.get("posted_at"),
            job_record.get("found_at"),
            normalize_optional_metadata(job_record.get("ingest_batch_id")),
            normalize_optional_metadata(job_record.get("source_query")),
            normalize_optional_metadata(job_record.get("import_source")),
            _nullable_int(job_record.get("source_registry_id")),
            identity.canonical_apply_url,
            identity.identity_key,
            job_record["raw_json"],
        ),
    )
    return int(cursor.lastrowid)


def find_duplicate_job_match(
    connection,
    job_record: Mapping[str, object],
) -> DuplicateJobMatch | None:
    apply_url = job_record.get("apply_url")
    if apply_url is not None:
        row = connection.execute(
            EXACT_APPLY_URL_MATCH_SQL,
            (apply_url,),
        ).fetchone()
        if row is not None:
            return DuplicateJobMatch(
                job_id=int(row["id"]),
                rule="exact apply_url match",
                matched_value=apply_url,
            )

    identity = build_job_identity(job_record)
    if identity.canonical_apply_url is not None:
        row = connection.execute(
            CANONICAL_APPLY_URL_MATCH_SQL,
            (identity.canonical_apply_url,),
        ).fetchone()
        if row is not None:
            return DuplicateJobMatch(
                job_id=int(row["id"]),
                rule="canonical apply_url match",
                matched_value=identity.canonical_apply_url,
            )

    if not _should_use_identity_key_match(job_record):
        return None

    row = connection.execute(
        IDENTITY_KEY_MATCH_SQL,
        (identity.identity_key,),
    ).fetchone()
    if row is None:
        return None
    return DuplicateJobMatch(
        job_id=int(row["id"]),
        rule="identity key match",
        matched_value=_describe_identity_match(job_record),
    )


def find_duplicate_job_id(
    connection,
    job_record: Mapping[str, object],
) -> int | None:
    match = find_duplicate_job_match(connection, job_record)
    if match is None:
        return None
    return match.job_id


def get_ingest_batch_summary(
    database_path: Path,
    *,
    batch_id: str,
) -> IngestBatchSummary | None:
    with closing(connect_database(database_path)) as connection:
        row = connection.execute(
            GET_INGEST_BATCH_SUMMARY_SQL,
            (batch_id,),
        ).fetchone()
    if row is None:
        return None
    return IngestBatchSummary(
        batch_id=str(row["ingest_batch_id"]),
        source_query=_nullable_text(row["source_query"]),
        import_source=_nullable_text(row["import_source"]),
        job_count=int(row["job_count"]),
    )


def record_session_history(
    database_path: Path,
    *,
    manifest_path: Path,
    item_count: int,
    launchable_count: int,
    batch_id: str | None,
    source_query: str | None,
    created_at: str | None = None,
) -> int:
    with closing(connect_database(database_path)) as connection:
        cursor = connection.execute(
            SESSION_HISTORY_INSERT_SQL,
            (
                str(manifest_path),
                item_count,
                launchable_count,
                normalize_optional_metadata(batch_id),
                normalize_optional_metadata(source_query),
                normalize_optional_metadata(created_at),
            ),
        )
        connection.commit()
    return int(cursor.lastrowid)


def list_recent_session_history(
    database_path: Path,
    *,
    limit: int,
) -> tuple[SessionHistoryEntry, ...]:
    if limit < 1:
        raise ValueError("limit must be at least 1")

    with closing(connect_database(database_path)) as connection:
        rows = connection.execute(
            LIST_RECENT_SESSION_HISTORY_SQL,
            (limit,),
        ).fetchall()
    return tuple(_session_history_entry_from_row(row) for row in rows)


def get_session_history_entry(
    database_path: Path,
    *,
    session_id: int,
) -> SessionHistoryEntry | None:
    with closing(connect_database(database_path)) as connection:
        row = connection.execute(
            GET_SESSION_HISTORY_BY_ID_SQL,
            (session_id,),
        ).fetchone()
    if row is None:
        return None
    return _session_history_entry_from_row(row)


def jobs_table_columns(connection) -> tuple[str, ...]:
    return _table_columns(connection, "jobs")


def initialize_schema_connection(
    connection,
    *,
    backfill_identity: bool = True,
    include_secondary_indexes: bool = True,
) -> None:
    _initialize_schema_connection(
        connection,
        backfill_identity=backfill_identity,
        include_secondary_indexes=include_secondary_indexes,
    )


def _initialize_schema_connection(
    connection,
    *,
    backfill_identity: bool,
    include_secondary_indexes: bool,
) -> None:
    if backend_name_for_connection(connection) == "postgres":
        for statement in POSTGRES_BASE_SCHEMA_STATEMENTS:
            connection.execute(statement)
    else:
        connection.executescript(SCHEMA_SQL)
    _ensure_jobs_columns(connection)
    if backend_name_for_connection(connection) == "sqlite":
        connection.executescript(POST_SCHEMA_SQL)
    elif include_secondary_indexes:
        for statement in POSTGRES_SECONDARY_INDEX_STATEMENTS:
            connection.execute(statement)
    if backfill_identity:
        _backfill_job_identity_columns(connection)


def _ensure_jobs_columns(connection) -> None:
    existing_columns = set(_table_columns(connection, "jobs"))
    required_columns = {
        "ingest_batch_id": "TEXT",
        "source_query": "TEXT",
        "import_source": "TEXT",
        "source_registry_id": "BIGINT" if backend_name_for_connection(connection) == "postgres" else "INTEGER",
        "canonical_apply_url": "TEXT",
        "identity_key": "TEXT",
    }
    for column_name, column_type in required_columns.items():
        if column_name in existing_columns:
            continue
        connection.execute(f"ALTER TABLE jobs ADD COLUMN {column_name} {column_type}")


def _backfill_job_identity_columns(connection) -> None:
    rows = connection.execute(
        """
        SELECT
            id,
            source,
            source_job_id,
            company,
            title,
            location,
            apply_url,
            portal_type
        FROM jobs
        WHERE canonical_apply_url IS NULL
           OR identity_key IS NULL
        """
    ).fetchall()
    for row in rows:
        identity = build_job_identity(row)
        connection.execute(
            """
            UPDATE jobs
            SET canonical_apply_url = ?,
                identity_key = ?
            WHERE id = ?
            """,
            (
                identity.canonical_apply_url,
                identity.identity_key,
                int(row["id"]),
            ),
        )


def _session_history_entry_from_row(row) -> SessionHistoryEntry:
    return SessionHistoryEntry(
        session_id=int(row["id"]),
        manifest_path=Path(str(row["manifest_path"])),
        item_count=int(row["item_count"]),
        launchable_count=int(row["launchable_count"]),
        batch_id=_nullable_text(row["ingest_batch_id"]),
        source_query=_nullable_text(row["source_query"]),
        created_at=str(row["created_at"]),
    )


def _table_columns(connection, table_name: str) -> tuple[str, ...]:
    return table_columns_from_connection(connection, table_name)


def _should_use_identity_key_match(job_record: Mapping[str, str | None]) -> bool:
    return job_record.get("apply_url") is None or job_record.get("source_job_id") is not None


def _describe_identity_match(job_record: Mapping[str, str | None]) -> str:
    source_job_id = _nullable_text(job_record.get("source_job_id"))
    if source_job_id is not None:
        anchor = (
            _nullable_text(job_record.get("portal_type"))
            or _nullable_text(job_record.get("source"))
            or "unknown"
        )
        return f"{anchor} | source_job_id {source_job_id}"
    return " | ".join(
        value
        for value in (
            _nullable_text(job_record.get("source")) or "source missing",
            _nullable_text(job_record.get("company")) or "company missing",
            _nullable_text(job_record.get("title")) or "title missing",
            _nullable_text(job_record.get("location")) or "location missing",
        )
    )


def _nullable_text(value: object) -> str | None:
    if value is None:
        return None
    if isinstance(value, str):
        normalized_value = value.strip()
        return normalized_value or None
    return str(value)


def _nullable_int(value: object) -> int | None:
    if value is None:
        return None
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        normalized_value = value.strip()
        if not normalized_value:
            return None
        try:
            return int(normalized_value)
        except ValueError:
            return None
    return None
